
/**
* FileInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* sábado 25 de noviembre de 2023 01:33:59 PM CST
*/

public interface FileInterfaceOperations 
{
  short contarLineas (String nombrearchivo);
  short cuentavocales (String nombrearchivo);
  void escribe (String nombreArchivoDestino);
  void imprimir ();
  void respaldar (String nombrearchivo);
  void copiar (String nombrearchivodestino);
  void renombrar (String nombrearchivo);
  void eliminar (String nombrearchivo);
} // interface FileInterfaceOperations
