
/**
* FileInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* viernes 24 de noviembre de 2023 08:51:25 AM CST
*/

public interface FileInterface extends FileInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileInterface
