
/**
* FileInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* viernes 24 de noviembre de 2023 08:51:25 AM CST
*/

public interface FileInterfaceOperations 
{
  byte[] downloadFile (String fileName);
} // interface FileInterfaceOperations
