
/**
* FileInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileInterface.idl
* sábado 25 de noviembre de 2023 01:33:59 PM CST
*/

public interface FileInterface extends FileInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileInterface
